language: node_js
node_js:
- "6.10"
env:
- LAMBDA_FUNCTION=helloworld
- LAMBDA_FUNCTION=lambda2
deploy:
  provider: lambda
  function_name: $LAMBDA_FUNCTION
  region: "us-east-1"
  role: "arn:aws:iam::103496338665:role/deploy"
  runtime: "nodejs6.10"
  handler_name: "handler"
  imeout: 15
  memory_size: 1024
script: cd $LAMBDA_FUNCTION && npm install